### ISSUE TITLE
tsup setup

### ISSUE THREAD

**Issue by patricklafrance** [workleap/wl-web-configs#17]
Similarly to our other tools, `tsup` should have it's own `tsup.config.js` or `tsup.config.json` file instead of being configured in the `package.json` file.

Furthermore, since we are using PNPM, `devDependencies` should be declared in every package instead of the monorepo root. `tsup` dependency is currently problematic.

**Comment by alexasselin008** [comment]
> Similarly to our other tools, tsup should have it's own tsup.config.js or tsup.config.json file instead of being configured in the package.json file.

No problem

> Furthermore, since we are using PNPM, devDependencies should be declared in every package instead of the monorepo root. tsup dependency is currently problematic.

I'm not so sure about that. I was looking at Chakra UI, and they have tsup at the root only, instead of in each packages.

 I would prefer having it at the root only, since i want this dependency to be the same across all my packages

**Comment by patricklafrance** [comment]
> I'm not so sure about that. I was looking at Chakra UI, and they have tsup at the root only, instead of in each packages.
> 
> I would prefer having it at the root only, since i want this dependency to be the same across all my packages

I get it, it's faster to bumb the version this way. I am not sure why Chakra UI is doing it this way thought as it's not how PNPM is intended to work.

> When installing dependencies with npm or Yarn Classic, all packages are hoisted to the root of the modules directory. As a result, source code has access to dependencies that are not added as dependencies to the project.
> 
> By default, pnpm uses symlinks to add only the direct dependencies of the project into the root of the modules directory.

Source: https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory

Adding `devDependencies` at the root of the monorepo has always caused ambiguity IMO as developpers must remember to make a conscious decision wether the dependency is used by all the packages and should be added at the root of the monorepo or the dependency is only used by a single or a few packages and should be added as direct `devDependencies` of a single or few packages.

It's seem trivial for `tsup` but for other dependencies it might not be.

Also, when adding `devDependencies` at the root of the monorepo, as time goes by, it becomes harder to say which dependencies are used by which packages as team members change and that knowledge is forgotten. You end up with unused dependencies installed because it's too hard to say which one are still used.

Overall, adding `tsup` as a direct `devDependencies` might be more painful short term but I believe it will pay off overtime.

**Comment by patricklafrance** [comment]
I searched to find other popular projects repos using PNPM to find out what they are doing. While it's not all black or white, most seems to be adding `devDependencies` per package.

- https://github.com/vercel/turbo/blob/main/packages/create-turbo/package.json
- https://github.com/vercel/next.js/blob/canary/packages/next/package.json
- https://github.com/TanStack/query/blob/main/packages/eslint-plugin-query/package.json
- https://github.com/vitejs/vite/blob/main/packages/vite/package.json
- https://github.com/withastro/astro/blob/main/packages/webapi/package.json
- https://github.com/prisma/prisma/blob/main/packages/client/package.json
- https://github.com/sveltejs/kit/blob/master/packages/kit/package.json
