### ISSUE TITLE
When using `@workleap/eslint-plugin` and extends `@workleap/web-application` in `.eslintrc.json` we get error about missing rule definition

### ISSUE THREAD

**Issue by ofrogon** [workleap/wl-web-configs#31]
When configuring EsLint for the project and using `@workleap/eslint-plugin`, in the `.eslintrc.json` like this:

```json
{
    "$schema": "https://json.schemastore.org/eslintrc",
    "root": true,
    "extends": "plugin:@workleap/web-application"
}
```

As it is documented [here](https://github.com/workleap/wl-web-configs/tree/main/packages/eslint-plugin#web-application). But I get this error from EsLint for each file:

```
ESLint: Definition for rule '@workleap/strict-css-modules-names' was not found.(@workleap/strict-css-modules-names)
```

Some more information:
- Package manager: PNPM v8.4.0
- Node: v18.16.0
- EsLint: v8.40.0
- OS: Win 10

**Comment by patricklafrance** [comment]
I have the same issue in @squide.
