### ISSUE TITLE
Add a config for tsup

### ISSUE THREAD

**Issue by patricklafrance** [workleap/wl-web-configs#46]
I believe that we now know enough about [tsup](https://tsup.egoist.dev/) to add a shared config to this project.

The shared config should strictly target TS libraries. We have a few examples in [squide](https://github.com/workleap/wl-squide).

I really like tsup's native `defineConfig` function. I believe we should develop something around this.

We could either export our own `defineConfig` function pre-configured with our defaults or a JSON config that the end user would have to pass to tsup's native `defineConfig` function.

**Comment by alexasselin008** [comment]
Duplicates  of https://github.com/workleap/wl-web-configs/issues/27

**Comment by patricklafrance** [comment]
Haha, oopsy, closing this one then!
