### ISSUE TITLE
Removed "target" and "sourceMaps" from TS configs

### ISSUE THREAD

**Issue by patricklafrance** [workleap/wl-web-configs#64]
Since we only lint with `tsc` and use `tsup` to transpile code, I don't think we need the `target` and `sourceMaps` fields in our TS configs as they are strictly related to transpilation.

Therefore, we should remove them.

**Comment by alexasselin008** [comment]
sourceMaps yes
target impacts the linting a little. I think it changes the default value of "lib". I would keep it to avoid undesirable changes

**Comment by patricklafrance** [comment]
Ok, sure then only `sourceMaps`

**Comment by patricklafrance** [comment]
Are you sure `target` really have an impact when linting?

I thought about this and I feel like we could remove `target` and `module`.

- `target` is the output environment that the code will be compiled for, which doesn't really feel like something that `tsc` would need for linting (that would be ESLint)
- `module` is the output module resolution system that the code will be compiled for which also something that `tsc` would need for linting (also would be ESLint here)

**Comment by alexasselin008** [comment]
According to ts' documentation: 

> Changing target also changes the default value of [lib](https://www.typescriptlang.org/tsconfig#lib). You may “mix and match” target and lib settings as desired, but you could just set target for convenience.

Then the lib documentation: 
> TypeScript includes a default set of type definitions for built-in JS APIs (like Math), as well as type definitions for things found in browser environments (like document). TypeScript also includes APIs for newer JS features matching the [target](https://www.typescriptlang.org/tsconfig#target) you specify; for example the definition for Map is available if [target](https://www.typescriptlang.org/tsconfig#target) is ES6 or newer.

So `target` doesn't affect linting directly, but it affects `lib`, which affects linting

**Comment by patricklafrance** [comment]
Ok sounds good for target then, let's keep it.

**Comment by patricklafrance** [comment]
Seems like sourcemaps is already set to false, closing!
